---
# Editing Enviroment File
- name: Replace NUXT_ENV_API_BASE_URL Value in env file
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_API_BASE_URL='
    line: NUXT_ENV_API_BASE_URL=/
    state: present
  register: API_BASE_URL

- name: Replace PROJECT_NAME in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_PROJECT_NAME='
    line: NUXT_ENV_PROJECT_NAME=ingot-partners
    state: present
  register: PROJECT_NAME

- name: Replace PORTAL_TYPE in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_PORTAL_TYPE='
    line: NUXT_ENV_PORTAL_TYPE=partners
    state: present
  register: PORTAL_TYPE

- name: Comment a line in env file
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commentinenv

- name: Comment NUXT_HOST  in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '(^NUXT_HOST=localhost)'
    line: '# \1'
    backrefs: yes
    state: present
  register: NUXT_HOST

- name: Replace NUXT_ENV_PROXY_TARGET_BASE_URL in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_PROXY_TARGET_BASE_URL='
    line: NUXT_ENV_PROXY_TARGET_BASE_URL=https://dev.ingotbrokers.com
    state: present
  register: PROXY_TARGET_BASE_URL

- name: Replace NUXT_ENV_TRANSLATIONS_API_URL in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_TRANSLATIONS_API_URL='
    line: NUXT_ENV_TRANSLATIONS_API_URL=https://dev.ingotbrokers.com
    state: present
  register: TRANSLATIONS_API_URL

- name: Replace NUXT_ENV_DEFAULT_ENTITY Value in Env File
  lineinfile:
    path: "{{ destdir[5] }}"
    regexp: '^NUXT_ENV_DEFAULT_ENTITY='
    line: NUXT_ENV_DEFAULT_ENTITY=dev.ingotbrokers.com
    state: present
  register: DEFAULT_ENTITY
