---

- name: Check API URL Status
  uri:
    url: https://api.ingotbrokers.com/v1/website/contact-requests
    method: POST
    body_format: json
    body: '{"name":"testting","email":"testting@gmail.com","message":"testting","phone_code":"123","phone_number":"123456789","contact_request_subject_id":"1"}'
    headers:
      content_type: "application/json"
      entity: "www.ingotbrokers.com"
      language: "en"
      connection: "keep-alive"
      Accept: "application/json"
    #set_cookie: '{"i18n_redirected=ar; Path=/; Expires=Wed, 18 Jan 2024 14:15:00 GMT; SameSite=Lax"}'
    follow_redirects: all
    return_content: false
    validate_certs: false
    status_code: [422]
  #changed_when: status_code != 422
  #when: url_check.status == 200 or url_check.status == 422
  #when: "code: 422"
  register: api_status

- name: Check API URL Status
  assert:
    that: api_status.status == 422

- name: Ansible Script to Send Emails
  mail:
    host: smtp.office365.com
    port: 587
    username: ingotadmin@ingotbrokers.com
    password: Wax92237
    to: q.shahrour@ingotbrokers.com
    subject: Ansible Alert Email
    body: "This is Alert Email sent by Ansible, to inform you that Error 404 accured"
    sender: ingotadmin@ingotbrokers.com
  register: mail_sent


  #- name: Print Status Code
  #debug:
  #msg: "Status code: {{ url_check.status }}"
  #debug: var=url_check
    #msg: "Status code: {{ url_check.status }}"
    
    #status_code: 200
  #changed_when: "status_code == 200"
    #status_code: 200
  #failed_when: "status_code != 200"
